---
- hosts: all
  connection: local
  gather_facts: False

  tasks:
  - name: Show Global Counters
    panos_op:
      ip_address: '{{ inventory_hostname }}'
      api_key: '{{ vault_api_key }}'
      cmd: show counter global
    delegate_to: localhost
    register: counters

  - name: Parse Aysymmetric Drop Rate
    xml:
      xmlstring: "{{ counters.stdout_xml }}"
      content: "text"
      xpath: "//entry[name='flow_tcp_non_syn']/rate"
    delegate_to: localhost
    ignore_errors: True
    register: drop_rate

  - name: Output
    debug:
      msg: "Asymmetric Drop Rate: {{ drop_rate.matches[0].rate }}"
    when: drop_rate.matches is defined

  - name: Output
    debug:
      msg: "Asymmetric Drop Rate: N/A"
    when: drop_rate.matches is undefined
...