---
- name: Configure Local Admins
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Configure Local Admins
      block:
        - name: Remove Default Local Administrator
          paloaltonetworks.panos.panos_administrator:
            provider: "{{ provider }}"
            admin_username: "admin"
            state: absent
          notify: Commit Changes Partial

        - name: Configure Local Administrator
          paloaltonetworks.panos.panos_administrator:
            provider: "{{ provider }}"
            admin_username: "{{ username }}"
            admin_password: "{{ password }}"
            superuser: true
          notify: Commit Changes Partial

  handlers:
    - name: Commit Changes Partial
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ provider }}"
        admins: ["{{ provider.username }}"]
