---
- name: Dynamic Content Upgrade
  hosts: all
  connection: local
  gather_facts: False

  tasks:
    - name: Update Content to Latest Version
      panos_dynamic_updates:
        provider: "{{ provider }}"
