---
- name: Dynamic Content Upgrade
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Update Content to Latest Version
      paloaltonetworks.panos.panos_dynamic_updates:
        provider: "{{ provider }}"
