---
- name: Run Exec Command
  hosts: all
  gather_facts: false

  tasks:
    - name: Execute Operational Command
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: "{{ command }}"
      delegate_to: localhost
      register: result

    - ansible.builtin.debug:
        var: result.stdout_lines[0]
