---
- name: Get Device State Snapshot
  hosts: all
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Get PAN-OS Facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset: ["system"]

    - name: Get Current Date/Time
      ansible.builtin.command:
        cmd: env TZ="America/Los_Angeles" date +"%Y%m%dT%H%m%S"
      changed_when: false
      register: date_output

    - name: Set Date Fact
      ansible.builtin.set_fact:
        date: "{{ date_output.stdout }}"

    - name: Set Facts
      ansible.builtin.set_fact:
        device_state_snapshot_main: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_{{ date }}.txt"
        device_state_snapshot_routes: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_routes_{{ date }}.csv"
        device_state_snapshot_ospf_neighbors: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_ospf_neighbors_{{ date }}.csv"
        device_state_snapshot_interfaces: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_interfaces_{{ date }}.csv"
        device_state_snapshot_arp_cache: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_arp_cache_{{ date }}.csv"
        device_state_snapshot_ts_agents: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_ts_agents_{{ date }}.csv"
        device_state_snapshot_userid_agents: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_userid_agents_{{ date }}.csv"
        device_state_snapshot_vpn_flows: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_snapshot_vpn_flows_{{ date }}.csv"
        device_state_cfg: "{{ playbook_dir }}/output/{{ inventory_hostname_short }}_device_state_cfg_{{ date }}.tgz"

    - name: Ensure Output Directory Exists
      ansible.builtin.file:
        state: directory
        path: "{{ playbook_dir }}/output"
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Save Configuration Snapshot
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: save config to preflight_{{ date }}.xml
      delegate_to: localhost
      when: save_config_snapshot | bool

    - name: Export Device State
      paloaltonetworks.panos.panos_export:
        provider: "{{ provider }}"
        category: device-state
        filename: "{{ device_state_cfg }}"
      delegate_to: localhost
      when: save_config_snapshot | bool

    - name: show system info
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show system info
      delegate_to: localhost
      register: system_info

    - name: show high-availability state
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show high-availability state
      delegate_to: localhost
      register: ha_state

    - name: show interface all
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: <show><interface>all</interface></show>
        cmd_is_xml: true
      delegate_to: localhost
      register: interface_info

    - name: show arp all
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: <show><arp><entry name = 'all'/></arp></show>
        cmd_is_xml: true
      delegate_to: localhost
      register: arp_cache

    - name: show routing route
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show routing route
      delegate_to: localhost
      register: route_table

    - name: show routing protocol ospf neighbor
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show routing protocol ospf neighbor
      delegate_to: localhost
      register: ospf_neighbors

    - name: show session info
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show session info
      delegate_to: localhost
      register: session_info

    - name: show vpn flow
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show vpn flow
      delegate_to: localhost
      register: vpn_flows

    - name: show user user-id-agent statistics
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show user user-id-agent statistics
      delegate_to: localhost
      register: user_id_agent_stats

    - name: show user ts-agent statistics
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show user ts-agent statistics
      delegate_to: localhost
      register: ts_agent_stats

    - name: show panorama-status
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show panorama-status
      delegate_to: localhost
      register: panorama_status

    - name: show logging-status
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show logging-status
      delegate_to: localhost
      register: logging_status

  post_tasks:
    - name: Render Main Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/main.j2
        dest: "{{ device_state_snapshot_main }}"
      delegate_to: localhost

    - name: Render Route Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/routes.j2
        dest: "{{ device_state_snapshot_routes }}"
      delegate_to: localhost

    - name: Render OSPF Neighbor Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/ospf_neighbors.j2
        dest: "{{ device_state_snapshot_ospf_neighbors }}"
      delegate_to: localhost

    - name: Render Interface Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/interfaces.j2
        dest: "{{ device_state_snapshot_interfaces }}"
      delegate_to: localhost

    - name: Render ARP Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/arp_cache.j2
        dest: "{{ device_state_snapshot_arp_cache }}"
      delegate_to: localhost

    - name: Render TS Agent Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/ts_agents.j2
        dest: "{{ device_state_snapshot_ts_agents }}"
      delegate_to: localhost

    - name: Render User-ID Agent Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/userid_agents.j2
        dest: "{{ device_state_snapshot_userid_agents }}"
      delegate_to: localhost

    - name: Render VPN Flow Template
      ansible.builtin.template:
        src: templates/device_state_snapshot/vpn_flow.j2
        dest: "{{ device_state_snapshot_vpn_flows }}"
      delegate_to: localhost

    - name: Find Files to Attach
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/output"
        patterns: "*"
      register: files

    - name: Mail Report
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        subject: "{{ inventory_hostname_short | upper }} Device State Snapshot"
        body: Attached please find the device state snapshot files for {{ inventory_hostname_short | upper }}.
        from: "{{ smtp_from }}"
        to:
          - "{{ smtp_to }}"
        attach: "{{ files.files | json_query('[].path') }}"
      ignore_errors: true
      delegate_to: localhost
