---
- name: Show System Resources
  hosts: all
  connection: local
  gather_facts: False

  tasks:
    - name: Show System Resources
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: show running resource-monitor
      delegate_to: localhost
      register: sys_resources

    - name: Output System Resource Monitor
      ansible.builtin.debug:
        var: sys_resources.stdout_lines[0]
